### ISSUE TITLE
Replace placeholders with SVGs for income/expense/money on hand icons

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#16]
[SVGs (2).zip](https://github.com/raft-tech/cfgov-refresh/files/4554249/SVGs.2.zip)
Short description explaining the high-level reason for the new issue.

## Current behavior

- All _Money on hand_, _Income_ and _Expense_ icons are currently placeholders.  

## Expected behavior

- Please replace the placeholders with the attached SVGs

**Comment by mgreen-simplethread** [comment]
This is done and will be pushed up to stage early Monday.

**Comment by MissyM2** [comment]
@mgreen-simplethread I do not see all the icons when I look at this on my mobile.  I see a few..

**Comment by LesliePerucci** [comment]
@mgreen-simplethread  All Income icons should be color hex #257675. All expense Icons should be color hex #B4267A. All icons should be the same size.

**Comment by mgreen-simplethread** [comment]
@LesliePerucci See https://github.com/raft-tech/cfgov-refresh/issues/32. Please send me updated assets and I'll add them in.

**Comment by mgreen-simplethread** [comment]
Icons in the category browser will now have the correct colors for expense vs. income. Will push to stage shortly.

**Comment by mgreen-simplethread** [comment]
Icons updated with updated versions from @LesliePerucci

**Comment by MissyM2** [comment]
Looks good.  All icons are the right color and size.  This is complete.
