### ISSUE TITLE
Fix padding issue in US Gov't website

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#22]
## Current behavior

- Viewing the app with certain viewports (including 320px width), bottom nav will overlay "US Gov't Website" notice in footer.

## Expected behavior

-  Additional padding underneath this element will prevent the overlay.

![Screen Shot 2020-04-30 at 6 21 45 PM](https://user-images.githubusercontent.com/34319929/80764879-a52a3b00-8b0f-11ea-8e7d-45231e074fe6.png)

**Comment by mgreen-simplethread** [comment]
Fixed and deployed to stage

**Comment by MissyM2** [comment]
I reviewed this and it is complete.
<img src="https://user-images.githubusercontent.com/34319929/80993070-727e8c00-8e08-11ea-8560-f2b3d9827801.png" width="250">
