### ISSUE TITLE
Fix alignment of form intro paragraph in wizard at desktop resolutions

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#23]
## Current behavior

- The intro paragraph in the wizard was not aligned at desktop resolutions

## Expected behavior

-  All text should be aligned properly.

**Comment by mgreen-simplethread** [comment]
Fixed

![Screenshot 2020-05-01 11 38 07](https://user-images.githubusercontent.com/45372816/80817885-3e089700-8ba0-11ea-9bdf-ef77fa2b42bb.png)

**Comment by MissyM2** [comment]
I reviewed this and it is complete.
