### ISSUE TITLE
Add bi-monthly payment option to rent

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#24]
Short description explaining the high-level reason for the new issue.

## Current behavior

- If a user selects 'recurring' when on the _Category Input Screen' for 'rent', then the frequency selects they can access are:  'weekly', and 'monthly'

## Expected behavior

-  The frequency selections for 'rent' should read all of the above, plus 'every two weeks'.

**Comment by mgreen-simplethread** [comment]
This is fixed. There is no bi-monthly (that was a misnomer on my part). I think what we want is actually bi-weekly, and that's what I added. Can also add semi-monthly if necessary, but that's confusing to most people who aren't familiar with the difference, IMO.

![Screenshot 2020-05-01 11 37 10](https://user-images.githubusercontent.com/45372816/80817795-1b767e00-8ba0-11ea-989b-efe761ca0d6f.png)
