### ISSUE TITLE
Make recurrence option labels in plain language.

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#25]
Short description explaining the high-level reason for the new issue.

## Current behavior

- When a user selects a frequency option on one of the _Category Input Screens', in the 'income area, the user sees bi-weekly as one of the options.  This may be confusing.

## Expected behavior

- The frequency option should read "every 2 weeks."

**Comment by MissyM2** [comment]
This is complete.
![Screen Shot 2020-04-30 at 6 32 29 PM](https://user-images.githubusercontent.com/34319929/80765683-9ba1d280-8b11-11ea-8fa6-ed3fb41a2abe.png)

**Comment by mgreen-simplethread** [comment]
This is complete and deployed to stage.

![Screenshot 2020-05-01 10 39 56](https://user-images.githubusercontent.com/45372816/80813679-7ad09000-8b98-11ea-9a68-ec8d3035925d.png)

**Comment by MissyM2** [comment]
On an actual phone, this 'Semi-monthly...' option is cut off.  Can we do something about this?
feedback requested.
@shubhi-raft @mgreen-simplethread 
<img src="https://user-images.githubusercontent.com/34319929/80989831-7956d000-8e03-11ea-8285-1876bb43e6b4.png" width="200">

**Comment by MissyM2** [comment]
@mgreen-simplethread  Please change 'Semi-monthly(two....)' to 'Twice a month'

**Comment by MissyM2** [comment]
This is complete.
<img width="300" src="https://user-images.githubusercontent.com/34319929/81573423-7a8f7c00-9372-11ea-9751-7daeb4acda67.jpg ">
