### ISSUE TITLE
Add two cta buttons to the 'More' screen as follows

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#27]
User would like the ability to send data to themselves in the form of a PDF.  For Usability Testing, Round 1, we will show the workflow/path that the user would take to get to the functionality.  There will be NO PDF or new email produced.  The expected functionality is described below.  

## Current behavior

-  There is no CTA for the app to Save Data or Save Calendar

## Expected behavior

- When the user clicks on the 'More' icon, the More screen appears.  
- There should be two additional CTA buttons under the 'Clear My Data' button.  
- The first should read 'Save Strategies'.  
- The second should read 'Save Calendar'.  
- When a user clicks on either of these buttons, they should navigate to a dummy page that just has a text description of what the next steps are. 
- The background color should not be red.  Rather, it should be the same blue color that matches the other buttons in the app.

fyi @shubhi-raft

**Comment by mgreen-simplethread** [comment]
This is done and deployed to stage

**Comment by MissyM2** [comment]
I reviewed this and it is complete.
<img src="https://user-images.githubusercontent.com/34319929/81202866-30368580-8f95-11ea-8974-0e550ff67821.jpg" height="250">
<img src="https://user-images.githubusercontent.com/34319929/81202868-30368580-8f95-11ea-8b2c-e97095cdf972.jpg" height="250">
<img src="https://user-images.githubusercontent.com/34319929/81202870-30368580-8f95-11ea-86fc-9043b78192a4.jpg" height="250">
<img src="https://user-images.githubusercontent.com/34319929/81202871-30cf1c00-8f95-11ea-937b-17e79a8b72e1.jpg" height="250">
