### ISSUE TITLE
Icon on homepage needs to be reverted back to previous icons that were originally there

### ISSUE THREAD

**Issue by LesliePerucci** [raft-tech/cfgov-refresh#31]
Short description explaining the high-level reason for the new issue.

## Current behavior

Money on hand icon is there. 

-

## Expected behavior
Original icons need to replace money on hand icon

## Steps to replicate behavior

1.

## Screenshots

__Current__
<img width="1250" alt="Screen Shot 2020-05-05 at 11 20 01 AM" src="https://user-images.githubusercontent.com/62399871/81083333-72db5d80-8ec2-11ea-8342-7c35fa786775.png">

__Expected__

<img width="490" alt="Screen Shot 2020-05-05 at 9 40 18 AM" src="https://user-images.githubusercontent.com/62399871/81083368-7e2e8900-8ec2-11ea-94d7-828145d60a0c.png">

**Comment by mgreen-simplethread** [comment]
@LesliePerucci The version of this asset that I currently have is, I'm pretty sure, just a PNG screenshot from the original InVision clickable prototype created by our predecessor agency. Would it be possible for you to get me a higher-res version of this as an either an optimized PNG or a JPEG (whichever is a smaller file)? The largest that I think the image ever displays on screen is 505x260, so I'd ideally need something 1010x520.

**Comment by mgreen-simplethread** [comment]
Either that, or an SVG if you've got access to the vector art for this. For the time being I'll put back the one I have.

**Comment by mgreen-simplethread** [comment]
Updated on staging

**Comment by MissyM2** [comment]
This is part of  my-money-calendar.  It is complete.  I am closing it.
