### ISSUE TITLE
Icon sizes are not the same. 

### ISSUE THREAD

**Issue by hstout7369** [raft-tech/cfgov-refresh#32]
Icons sizes are not consistent, so the items are not line up. 

<img width="1032" alt="Screen Shot 2020-05-05 at 3 01 31 PM" src="https://user-images.githubusercontent.com/59989395/81105058-63b7d800-8ee1-11ea-8198-2aa9bb6b3aca.png">

<img width="957" alt="Screen Shot 2020-05-05 at 11 43 18 AM" src="https://user-images.githubusercontent.com/59989395/81086422-78d33d80-8ec6-11ea-90fd-52b6533a7674.png">

<img width="673" alt="Screen Shot 2020-05-05 at 11 51 22 AM" src="https://user-images.githubusercontent.com/59989395/81104521-a2995e00-8ee0-11ea-88cd-dcbf6781711e.png">

<img width="1109" alt="Screen Shot 2020-05-05 at 11 51 48 AM" src="https://user-images.githubusercontent.com/59989395/81104524-a3ca8b00-8ee0-11ea-95a0-ae687ddc7de7.png">

**Comment by mgreen-simplethread** [comment]
@LesliePerucci The SVG's you sent me seem to all have different dimensions and aspect ratios. Can you give me some assets that all have the same size view box and dimensions? Whatever they're depicting can be sized any way it needs to be within that canvas, but it's a lot easier than me guessing and editing SVG element attributes trying to get it right.

**Comment by mgreen-simplethread** [comment]
Fixed on staging
