### ISSUE TITLE
Change Generic Expense/Income description sentence

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#33]
## Current behavior
Currently, the expense/income description sentence reads: “Enter your [Expense Name] details.”  

## Expected behavior
Change this to “Enter the details of your [Expense Name] Expense.” 

## Steps to replicate the behavior
This is a generic change targeted to all income and expenses, but the examples below highlight areas where this sentence structure is ambiguous and might cause confusion.
a.	Enter your pet details – change to “Enter the details of your pet expense.”
b.	Enter your education details. – change to “Enter the details of your education expense.”
c.	Enter your phone/cell details. – change to “Enter the details of your phone/cell expense.”

## Screenshots
![Picture1](https://user-images.githubusercontent.com/4583566/81188966-0163e380-8f84-11ea-9a37-3373fc5cba32.png)

**Comment by jbevis** [comment]
grabbing

**Comment by jbevis** [comment]
@RedNumberIX in order to make this change we'll need to account for the income categories as well. Would you like it to read...

"Enter the details of your job ---income---"

OR

"Enter the details of your job"

**Comment by RedNumberIX** [comment]
Let's stay consistent.
**Expenses:** "Enter the details of your [singular name] expense" 
**Income:** "Enter the details of your [singular name] income"
