### ISSUE TITLE
Change Expense titles to singular

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#34]
Short description explaining the high-level reason for the new issue.

## Current behavior
The specific expense titles listed below are plural, which creates grammatically incorrect sentences. (Example: “Enter your groceries details.”)

## Expected behavior
Change these titles to singular:
a.	Property Taxes – Change to “Property Tax”
b.	Groceries – change to “Grocery”
c.	Subscriptions – change to “Subscription”
d.	Pets – change to “Pet”
e.	Court-Ordered Expenses – Change to “Court-Ordered Fee”

## Screenshots
![Picture2](https://user-images.githubusercontent.com/4583566/81189261-64ee1100-8f84-11ea-9e15-81af88420363.png)

__Expected__

**Comment by jbevis** [comment]
grabbing
