### ISSUE TITLE
Change Income Acronym descriptions to all caps 

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#35]
Short description explaining the high-level reason for the new issue.

## Current behavior
Acronym descriptions currently appear in lowercase

## Expected behavior
When editing or entering the two income listings below the description uses the lower case when they should be in all-caps.   
a.	TANF – Incorrect: “Enter your tanf details.”
b.	SNAP – Incorrect: “Enter your snap details.”

## Screenshots

![Picture3](https://user-images.githubusercontent.com/4583566/81189652-d4640080-8f84-11ea-8bba-7092eb91a0fd.png)

**Comment by jbevis** [comment]
grabbing
