### ISSUE TITLE
Mention “Child Support” in “Other” Income details. 

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#36]
Short description explaining the high-level reason for the new issue.

## Current behavior
No mention of Child Support in the Other income entry details, as requested by Yulia

## Expected behavior
"Enter your other details" – change to “Enter the details of any other sources of income you might have including Child Support”

## Screenshots
![Picture4](https://user-images.githubusercontent.com/4583566/81189988-40deff80-8f85-11ea-8334-924d7e8d821c.png)

**Comment by mgreen-simplethread** [comment]
@RedNumberIX Fixed and deploying. I'm using the description the category already had - it just wasn't surfaced anywhere in the UI before now
