### ISSUE TITLE
Remove Fix-It Strategy for "Trash" & "Phone/Cell" Expenses

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#39]
## Current behavior
When a user goes into the red and a "Trash" OR "Phone/Cell" expense exists Fix-It Strategies generates the "Budget Billing" Strategy.

## Expected behavior
The "Budget Billing" strategy should **only** appear if one of the following three expense categories are selected: "Natural Gas, oil, Propane," "Water/Sewage," and "Electricity."

## Screenshots
![Picture7](https://user-images.githubusercontent.com/4583566/81192475-4722ab00-8f88-11ea-9e17-a7fe2611c89c.png)
![Picture8](https://user-images.githubusercontent.com/4583566/81193093-f6f81880-8f88-11ea-9243-404c8537ed92.png)

**Comment by mgreen-simplethread** [comment]
@RedNumberIX This is fixed and deploying to stage.

**Comment by rhunter64** [comment]
Issue Fixed.
