### ISSUE TITLE
Change Non-Due Date Fix-It Strategies Details to Singular

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#40]
## Current behavior
When a user goes into the red for a non-due date expense the copy appears in the plural. 
This shows incorrect sentences like the one below:
"Gas _were_ your largest expense this week not tied to a bill you are obligated to pay...."

![Picture9](https://user-images.githubusercontent.com/4583566/81201810-b5b93600-8f93-11ea-834d-5479dffcf14f.png)

## Expected behavior
Expense categories should be consistently in the singular form, so the format for all of these strategies should read: 

**Your** "[expense name] **expense was** your largest expense this week not tied to a bill you are obligated to pay. Consider spending a little less this week and a little more in weeks where you have fewer expenses or more income. "

This change is expected in the following Expense categories (all of which are designated Non-Due Date Expenses with Fix-It Strategies): Public Transportation, Gas, Easting Out, Groceries, Clothing, Hair/Cosmetics, and Fun Money.

**NOTE:** 
As the app currently stands the sentence structure only creates an error with the expense of gas. In all other instances, the correct verb tense of was/were is present in the app. (example: Fun money was your largest expense, Groceries were your largest expense, etc.) However, when the expenses are changed from plural to singular for consistency throughout the app ( as stated in ticket #34 ) this broader change will become necessary.

**Comment by jbevis** [comment]
grabbing
