### ISSUE TITLE
Due Date Fix-It Strategies Won't Appear (In Lesser Amounts)

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#42]
We were having an issue with the Fix-It Strategies not appearing and I believe I might have discovered the root cause of the problem. 

## Current behavior
If I go into the calendar and submit one entry for three separate expenses, (One for A Housing Expense, Due Date Expense, and Non-Due Date Expense). I only see two Fix-It Strategies. [See Fig 1]
![Fig1](https://user-images.githubusercontent.com/4583566/81416567-e2965600-9117-11ea-8542-97fba432c086.png)
In this example the Fix-It Strategy for the Due Date Expenses does not appear.

##The Issue
However, the code for the Due Date Expenses is there and I can make it appear if I adjust the amounts for the expenses. 

If I decrease the Housing expense so that it is the lowest of the three expenses the Fix It Strategy for the Due Date Expense appears! [See Fig 2]
![Fig2](https://user-images.githubusercontent.com/4583566/81416807-3f920c00-9118-11ea-9ce7-46070e3d5943.png)

A similar situation occurs if I increase the Due Date Expense so that it is the largest of the three expenses. [See Fig 3]
![Fig3](https://user-images.githubusercontent.com/4583566/81416865-59335380-9118-11ea-96a6-c1f298ea775f.png)

This change in data does not effect the appearance of the non-due date expenses in any way. This leads me to believe there is logic running in the background tied to both the Housing Expense and the Due Date expense that prevents the latter from appearing when it is the lesser of the two.

**Comment by jbevis** [comment]
Reviewing this for our next spring and will defer to @RedNumberIX and @MissyM2 

I believe you both are more familiar with how the fix-it strategies are supposed to work.

Do we know if this has been addressed through other tasking?

**Comment by MissyM2** [comment]
This is resolved.  See screenshot below.  Even if you add the same amount for all three categories (housing, due date and non-due date expenses) (in the screenshot, all three were $100 and the starting balance was $100), all three strategies appear.  I am closing this ticket.
