### ISSUE TITLE
Input/Edit screen save button has unexpected behavior

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#44]
Save button in Input/Edit screen does not return user to Calendar view when they are editing a recurring transaction.
fyi @shubhi-raft 

## Current behavior
- User, viewing  a recurring transaction in the _week block_, clicks edit to make changes.  The input/edit screen comes up.
-  User changes the **_Date_** and clicks save.
6. User is **not returned to the calendar view**.

## Expected behavior
- When the user clicks save, the user should navigate back to the Calendar.

## Screenshots

<img width="200" alt="Screen Shot 2020-05-13 at 2 58 38 PM" src="https://user-images.githubusercontent.com/34319929/81960180-8da68400-95de-11ea-9026-e0cb1b896dbc.png">

**Comment by jbevis** [comment]
Unable to replicate, and believe this issue was fixed during previous dev sprint.

closing.
