### ISSUE TITLE
Verify SNAP logic and integrate into UI

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#52]
Verify SNAP logic and integrate into UI.  The way that SNAP income appears in the UI has not been determined, yet.

fyi @shubhi-raft @meissadia @RedNumberIX @LesliePerucci @omnipresent07 @MissyM2 

## Current behavior

-  SNAP income is treated as regular income in the app.  That is, for income balance calculations, SNAP is considered just like any other income.  In reality, this _income_ is actually a _benefit_ that may only be used for groceries.  It is a form of _restricted income_.  

## Expected behavior

-  Balances need to correctly reflect that SNAP income has been just used for groceries and the user needs to understand how much money they have available for their use from both _regular income_ and _SNAP benefit income_.

## Screenshots

__Current__
In this scenario, I added $100 for starting balance.  I added $250/week (on Fridays) for job income and $75/money for SNAP benefit income.  I added electricity $85/month on the 23rd and rent payment of $850 on the first of the month.  I **have not added any groceries** but,  my _SNAP benefit_ $75 has been applied to other bills.

<img width="192" alt="Screen Shot 2020-06-15 at 9 12 40 AM" src="https://user-images.githubusercontent.com/34319929/84661472-66e2b280-aee8-11ea-9486-31ac18785a7a.png">

__Expected__

**Comment by jbevis** [comment]
Tracking thoughts:

Need to confirm if the below matches the UI, if so we can open a PR otherwise need more direction on UI.

<img width="839" alt="Screen Shot 2020-06-16 at 9 05 06 AM" src="https://user-images.githubusercontent.com/21065244/84792291-eb006d00-afb0-11ea-8a97-abd59500398c.png">

**Comment by jbevis** [comment]
Based on client feedback, UI has been updated to only have:
- Week Starting Balance
- Week ending balance
- SNAP ending balance (if SNAP has been added)

<img width="671" alt="Screen Shot 2020-06-16 at 4 36 30 PM" src="https://user-images.githubusercontent.com/21065244/84834927-c1b30180-afef-11ea-803d-e8121ac1249b.png">

**Comment by jbevis** [comment]
The logic is in place to handle the SNAP benefits, if this UI is approved I'll open a new PR to merge this work to our ```my-money-calendar``` branch to be deployed to CFPB.

**Comment by jbevis** [comment]
PR is up for review https://github.com/raft-tech/cfgov-refresh/pull/61

**Comment by shubhi-raft** [comment]
@jbevis 

SNAP benefit only applies to grocery and cannot be counted as regular income, and hence cannot be added to the weekly starting or ending balance. The current logic counts it as money available in the weeks after the benefit was added. 

Current Logic:

1. Week Starting Balance = income + job + any remaining money from last week + SNAP Money 
2. Weekly Ending Balance = Starting balance - expenses - SNAP Money
3. SNAP Balance = works fine = snap card - grocery

Week in which SNAP benefit is added: 
<img width="1264" alt="Screen Shot 2020-06-22 at 10 37 51 AM" src="https://user-images.githubusercontent.com/22622384/85302004-965c6680-b476-11ea-923d-6e0574a26687.png">

Week following the SNAP benefit was added:
<img width="1241" alt="Screen Shot 2020-06-22 at 10 40 02 AM" src="https://user-images.githubusercontent.com/22622384/85302135-c0ae2400-b476-11ea-8d9b-5d321699ec77.png">

Expected Logic:

1. Week Starting Balance = income + job + any remaining money from previous week [No SNAP Money]
2. Weekly Ending Balance = Starting balance - expenses [grocery to be included as an expense **if and only if** no SNAP money is left]
3. SNAP balance = works fine = SNAP card - grocery

**Comment by shubhi-raft** [comment]
@jbevis Logic looks good, however, need to refine formatting. 

### Issue 1:
Update text as stated below: 
Weekly Start**ing** Balance: 
Weekly End**ing** Balance:
Weekly End**ing** SNAP Balance: 

### Issue 2: 

Current Behavior
See screenshot - more than double digit moves to the next line. 
<img width="294" alt="Screen Shot 2020-06-26 at 1 50 21 PM" src="https://user-images.githubusercontent.com/22622384/85886774-a6e14980-b7b4-11ea-80be-882b81475ba2.png">

Expected Behavior
No matter the amount; text should be displayed on one line.

**Comment by jbevis** [comment]
@shubhi-raft 
I'll get the headers updated per the request.

With regard to the text always appearing on one line, it's a bit more involved. Depending on screen size at some point the element begins to run out of real estate and thus as part of the responsive nature of the app, the text will break to new lines. 

I agree that there should be a measure of visual consistency, but keeping it all on one line for smaller screens is going to look cramped.

I could add a css rule to drop the amounts below the label once the viewport is below a certain threshold, which would help with consistency

**Comment by shubhi-raft** [comment]
@jbevis let's try your proposed solution for visual consistency. if it works, great, if not, we will revert back. is that ok?

**Comment by jbevis** [comment]
Sounds good, I'll update and get changes pushed out for review.

**Comment by jbevis** [comment]
@shubhi-raft the requested changes are now live at https://cfgov-refresh-staging.herokuapp.com/mmt-my-money-calendar/
