### ISSUE TITLE
General Strategies Listing Order

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/cfgov-refresh#70]
Short description explaining the high-level reason for the new issue.

## Current behavior
- Save for Emergencies and Coronavirus appears at the bottom

## Expected behavior
- General Strategies should be prioritized as:
1. Save for Emergencies
2. Coronavirus related strategy
3. Anything else

## Steps to replicate behavior

1. NA

## Screenshots

__Current__
![IMG_810CA7BD8290-1](https://user-images.githubusercontent.com/22622384/85420750-9ffed080-b541-11ea-8e88-595b7bc8d05e.jpeg)

__Expected__
Reverse of above. 

## Note: Same order should appear in Fix-It Strategies

**Comment by MissyM2** [comment]
I have reordered the _General Strategies_ per the instructions above.  This is part of the PR that I submitted tonight.  I am moving this to _In Review.

fyi @shubhi-raft @jbevis @BarakStout

**Comment by MissyM2** [comment]
Based on @hstout7369 feedback, I made a change and both she and I tested it.  It is complete and ready to merge and be closed.

**Comment by jbevis** [comment]
Feature has been merged. Closing
