### ISSUE TITLE
Fix-It Strategy that Points to Generic Strategies

### ISSUE THREAD

**Issue by RedNumberIX** [raft-tech/cfgov-refresh#78]
## Current behavior
In the _rare_ event that no Fix-It Strategies are generated, a Fix-It Strategy appears that directs the user to view the Generic Strategies. 

![viewgeneralstrategies](https://user-images.githubusercontent.com/4583566/85760555-f3a72080-b6df-11ea-899c-ac5e97eaeb52.png)

This feature was created in an earlier iteration of the app before Generic Strategies were set to also appear under Fix-It Strategies, making them redundant. 

## Possibility 
It's exceptionally rare that a user would find this instance in the natural use of the app because they would need to: 
1. Enter no Housing Expenses at all (then also)
2. Enter no Due Date expenses or only those that have no strategy (then also)
3. Enter no Non-Due Date expenses or only those that have no strategy (then also)
4. Have a negative weekly ending balance. 

## Question
**How do we fix this redundant text?**
**A.** Remove the strategy altogether. - This would create just a blank white space between the Fix-It Strategy Title and the General Strategies.
**B.** Place some other content there in its place. - Since this is such a rare situation a generic message might be useful. (Example: "Based upon your weekly transactions we can't recommend any Fix-It Strategies. Make sure that you've entered in all of your expenses and income for the week then check back here later, otherwise review the generic strategies below.")

**Comment by shubhi-raft** [comment]
This should be a backlog item. Address it in the next tool refinement.

**Comment by MissyM2** [comment]
Changed copy of the message per Ryan's suggestion.  (The copy can be easily changed).  I tested this and it should be complete.  Moving to 'In Review.'
