### ISSUE TITLE
Fix-it Button should reflect the SNAP balance and the regular balance

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#83]
@jbevis 
**Testing on Staging server/Safari**:  I tested a few new scenarios and came up with the following issue:

Steps:
- $0 starting balance
- $90 SNAP benefit added for July 1, 2020
- $25 weekly groceries on Fridays, starting July 3, 2020
- move to the first week that goes into the red:  week of July 20

**Current Outcome**:
- Calendar color should be green because, it was agreed that, if the regular balance is $0 or above, the calendar will be **green**.  In this case, the regular balance is $0, so the color is correct.
- The _Fix-it_ message appears, saying "You are going to be in the red!" with a _Weekly End Balance_ :-$10.00 The regular _Weekly End Balance_ should be $0 and the _Weekly SNAP End Balance_ should be $-10.00.  

**Expected Outcome**:
- The information on the _Fix It_ message should say _Weekly End Balance_ is $0. 
- Consider adding the _Weekly SNAP End Balance_ to this.
- Question:  Should the _Fix-It_ message be triggered under either circumstance?
<img width="500" alt="Screen Shot 2020-06-26 at 12 06 55 PM" src="https://user-images.githubusercontent.com/34319929/85879122-ccb42180-b7a7-11ea-9974-6651aeccd7dd.png">

**Comment by MissyM2** [comment]
The calendar correct reflects ending balance now because of logic changes in the last Sprint.  Once the $90 SNAP balance is exhausted, the _Weekly End Balance_  reflects a negative and the week shows in red.  I am closing this ticket.
<img width="125" alt="Screen Shot 2020-07-28 at 6 34 37 PM" src="https://user-images.githubusercontent.com/34319929/88729258-6e10f900-d101-11ea-8bda-d4f112534f1f.png">

**Comment by BarakStout** [comment]
Needs more user research to confirm any potential problems with navigation and end-user comprehension of the interface.
