### ISSUE TITLE
Update Bottom Navigation

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/cfgov-refresh#84]
## Current behavior

- Bottom Navigation has 'add'

## Expected behavior

- Add should be replaced by 'Income/Expense'

## Screenshots

__Current__
![Screen Shot 2020-06-29 at 2 38 48 PM](https://user-images.githubusercontent.com/22622384/86043384-aba53800-ba16-11ea-924e-d1bc79e192dd.png)

@MissyM2

**Comment by MissyM2** [comment]
@shubhi-raft just want to check again...  I think I forgot to mention this.  The spacing was off when it was Income/Expense.  If you notice, that makes it the longest subtitle.  Income/Expense ends up being a 2 line title on most of the mobile devices.  It pushes the + up above the other icons.  I can change add the original title but it will be on 2 lines, pushing the + back up.  Let me know and I can make the change.
