### ISSUE TITLE
Week should be red if the ending balance is red

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#88]
Week should be red if the ending balance is red.

## Current behavior

-  Currently, the calendar turns red on the day that the balance goes below $0.  Alternatively, the calendar turns green on the day that the balance is $0 or above $0.  It remains that color until the condition changes.

## Expected behavior

- If the ending balance for the week is red, then the entire week should be red colored.
- Alternatively, if the ending balance for the week is green, then the entire week should be green-colored.

**Comment by shubhi-raft** [comment]
### Expected behavior
If the ending balance for the week is red, then the entire ~~previous~~ week should be red colored.
Alternatively, if the ending balance for the week is green, then the entire ~~previous~~ week should be green-colored.

@MissyM2 reviewed and updated.

**Comment by jbevis** [comment]
Merged. Closing.
