### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#89]
Client requested some format and copy changes.
fyi @shubhi-raft @BarakStout @jbevis 

## Expected behavior

- The headers to each of the notifications should be bolded (see screenshot)
- The first notification (after clicking the 'Go to Calendar' button) should be higher up so the downward arrow is visible. (see screenshot)

- Review the copy for each of the notifications and update based on the screen shots below.  These are changes the client just made.

## Screenshots

<img width="150" alt="jb2" src="https://user-images.githubusercontent.com/34319929/86386051-3bd5be00-bc5f-11ea-8c42-ce3eb49062c9.png">
<img width="500" alt="jb1" src="https://user-images.githubusercontent.com/34319929/86386052-3bd5be00-bc5f-11ea-9a69-1e621e37b1e0.png">

#copy for notifications
<img width="624" alt="Screen Shot 2020-07-02 at 12 30 34 PM" src="https://user-images.githubusercontent.com/34319929/86386781-3d53b600-bc60-11ea-9d77-856552fb77f7.png">
<img width="570" alt="Screen Shot 2020-07-02 at 12 30 25 PM" src="https://user-images.githubusercontent.com/34319929/86386784-3d53b600-bc60-11ea-894c-e364c8c43dfe.png">
<img width="538" alt="Screen Shot 2020-07-02 at 12 30 07 PM" src="https://user-images.githubusercontent.com/34319929/86386785-3dec4c80-bc60-11ea-9313-af086fd1bdd6.png">
<img width="623" alt="Screen Shot 2020-07-02 at 12 30 00 PM" src="https://user-images.githubusercontent.com/34319929/86386787-3dec4c80-bc60-11ea-82a0-cdd44ee53467.png">

**Comment by MissyM2** [comment]
@jbevis here is a communication from the thread...  it is the final communication that Serena gave on one of the notifications. 
<img width="515" alt="Screen Shot 2020-07-02 at 12 37 28 PM" src="https://user-images.githubusercontent.com/34319929/86387265-ef8b7d80-bc60-11ea-9798-0f2a9a758b87.png">

**Comment by jbevis** [comment]
@MissyM2 can you clarify.

Here is a screen shot from dev
![Screen Shot 2020-07-02 at 10 57 14 AM](https://user-images.githubusercontent.com/21065244/86389664-e647e400-bc53-11ea-8e04-e7ed7c258256.png)

What in the copy needs to change?

Maybe I'm missing a very small change, but the only thing I can tell in the screen shot above is a slight change to the body content for the SNAP notification. Also, is this captured in a document for reference. I am simply copy and pasting the text from the doc to the code so it should be matching exactly.

Also what is the context for Serena's comment? Remove that Line? Update to only be that line? More information would be helpful.

**Comment by jbevis** [comment]
@MissyM2 what browser was being used for the screen shots regarding the bold header?

**Comment by shubhi-raft** [comment]
@jbevis Chrome

**Comment by jbevis** [comment]
Thanks Shubhi, for the notification headline, when I view the staging app on my machine the bold header is in place (chrome, firefox, and safari all show it) Is anyone else not seeing the headlines bolded when they review the notifications on staging on their own computer?

**Comment by BarakStout** [comment]
@jbevis I see the headline being bold, but it is nearly a noticeable difference. Maybe consider adding a `font-weight: bold;` 

Current: 
![Screen Shot 2020-07-02 at 3 18 16 PM](https://user-images.githubusercontent.com/34528865/86400860-4bf99780-bc77-11ea-9bbf-a48b6b9d134d.png)

Updated:
![Screen Shot 2020-07-02 at 3 16 54 PM](https://user-images.githubusercontent.com/34528865/86400880-5582ff80-bc77-11ea-889a-445315cbd98b.png)

**Comment by shubhi-raft** [comment]
@jbevis also the arrow at the bottom of the modal overlaps with the selected tab for the bottom navigation and hence cannot be seen / may result in accessibility issues. 

<img width="1280" alt="Screen Shot 2020-07-02 at 11 42 54 AM" src="https://user-images.githubusercontent.com/22622384/86401474-4781ae80-bc78-11ea-81f5-da8d2f6b6526.png">

fyi @BarakStout

**Comment by jbevis** [comment]
@shubhi-raft @BarakStout @MissyM2 

Changes have been made and are ready for review on dev
https://cfgov-refresh-dev.herokuapp.com/mmt-my-money-calendar

**Comment by shubhi-raft** [comment]
Thanks. Tested and works as expected. 

--
Best,
Shubhi Mishra
HealthStar Informatics
1801 Old Reston Avenue, Suite 102,
Reston, VA, 20190
301-395-6823
http://healthstarinfo.com/

**Comment by jbevis** [comment]
Great!

@MissyM2 please review code changes and merge at earliest convenience.
