### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#91]
Client requested the following copy changes.
fyi @shubhi-raft @BarakStout @jbevis 

## Expected behavior
  
- [x]  Transaction header title should read `Week of..`
- [x]  Transaction header remove all "Weekly" 
- [x]  instances of `MyMoney Calendar` should be changed to `myMoney Calendar`
- [x]  Fix-it Strategy on `Split Rent Payments` should read `Split Rent Payment`

**Comment by MissyM2** [comment]
Changes are complete.

**Comment by jbevis** [comment]
https://github.com/raft-tech/cfgov-refresh/pull/95 has been merged. Closing.
