### ISSUE TITLE
Starting balance is incorrectly reading $0

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#92]
Starting balance logic needs to be adjusted.
fyi @shubhi-raft  @BarakStout @jbevis 

## Current behavior

- In the week that the user starts to use the app, the starting balance is $0 even if they have added a starting balance later in the week.

## Expected behavior

- In the week that a user starts to use the app, the starting balance should be the balance that the user entered, regardless of which day they enter it.

## Screenshots

<img width="200" src="https://user-images.githubusercontent.com/34319929/86387904-dcc57880-bc61-11ea-9c8e-ee045ac5f7e1.png">

**Comment by MissyM2** [comment]
If the Weekly Starting Balance category is present in a given week, then that is the balance showing in the _Weekly Starting Balance_ field in the Calendar detail header.  This is complete and ready for review.

**Comment by jbevis** [comment]
https://github.com/raft-tech/cfgov-refresh/pull/95 has been merged. Closing
