### ISSUE TITLE
SNAP added to Fix-It Income

### ISSUE THREAD

**Issue by rhunter64** [raft-tech/cfgov-refresh#98]
Short description explaining the high-level reason for the new issue.

## Current behavior
SNAP is _not_ added to income on the Calendar Summary, but it _is_ added to income on Fix-It Strategies.

## Expected behavior

SNAP should be excluded from income because the user can't spend them on anything else but groceries. Furthermore, the Fix-It function doesn't factor them in when deciding whether or not to show the Fix-It button. This makes it confusing when situations occur like in the screenshot below, so it appears like the user should have a $200 surplus of funds.   

-

## Steps to replicate behavior

1. Enter a SNAP benefit.
2. Enter an expense that is greater than the SNAP benefit to cause the user to go into the red.
3. Click on the Fix-It Button, and view the summary.

## Screenshots

![SNAP Problem](https://user-images.githubusercontent.com/68604244/88414228-8227c400-cdaa-11ea-8064-f5f88c5e0c2a.jpg)

**Comment by jbevis** [comment]
Best estimate on LOE: 3 - 5 points.

**Comment by jbevis** [comment]
@rhunter64 to clarify.

In the scenario above, the expected income amount on the fix-it view should be $0.00, correct?

**Comment by rhunter64** [comment]
Yes, it should be $0

**Comment by jbevis** [comment]
PR is up and pending review
https://github.com/raft-tech/cfgov-refresh/pull/104

**Comment by rhunter64** [comment]
@MissyM2 @jbevis 
This works as expected.
