### ISSUE TITLE
Starting Balance added to Fix-It Income

### ISSUE THREAD

**Issue by rhunter64** [raft-tech/cfgov-refresh#99]
## Current behavior
The first week a user inputs in the app their Money-on-Hand balance is labeled under the "Starting Balance" Transaction. On the calendar summary screen, that entry is reflected in that week's starting balance. However, if a user goes into the red on the first week, the transaction is considered "Income" rather than the starting balance. 

## Expected behavior
The starting balance transaction on the calendar summary should contribute to the Starting balance on the Fix-It Strategies Summary Page. 

## Steps to replicate behavior

1. Start the App Fresh
2. Enter any amount into the Money-on-hand Wizard.
3. Enter an expense that is more than the Starting Balance (so you go into the red).
4. Click the Fix-It button and read the Summary on the Fix-It Strategy Page. 

## Screenshots

![Starting Balance](https://user-images.githubusercontent.com/68604244/88415330-4a218080-cdac-11ea-8acb-d9f6f228567b.jpg)

**Comment by jbevis** [comment]
Best estimate for LOE: 2 - 3 points.

**Comment by jbevis** [comment]
PR is up and pending review
https://github.com/raft-tech/cfgov-refresh/pull/104

**Comment by rhunter64** [comment]
@MissyM2 @jbevis 
This works as expected.
